{{- if and .Values.azure.storage (hasKey .Values.azure.storage "account") }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "helm.fullname" . }}-azure-csi
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  skuName: {{ .Values.azure.storage.sku }} # may need to bind to an existing share: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/storageclass-azurefile-existing-share.yaml
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
  - nobrl  # disable sending byte range lock requests to the server and for applications which have challenges with posix locks
{{- end }}