{{- if and .Values.azure (hasKey .Values.azure "keyVaultName") .Values.azure.keyVaultName }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "helm.fullname" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: {{ .Values.azure.usePodIdentity | default false | quote }}
    useVMManagedIdentity: {{ .Values.azure.useVMManagedIdentity | default false | quote }}
    clientID: {{ .Values.azure.clientid | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.azure.kvSecrets }}
        - |
          objectName: {{ . | quote }}
          objectType: secret
        {{- end }}
  secretObjects:
    - secretName: {{ include "helm.fullname" . }}-secrets
      type: Opaque
      data:
        {{- range .Values.azure.kvSecrets }}
        - key: {{ . | lower | replace "_" "-" }}
          objectName: {{ . | quote }}
        {{- end }}
{{- end }}