{{- if hasKey .Values "debug" }}
apiVersion: v1
kind: Pod
metadata:
  name: debug-cli
spec:
  serviceAccountName: {{ .Values.azure.storage.serviceaccount | quote }}
  serviceAccount: {{ .Values.azure.storage.serviceaccount | quote }}
  containers:
    - name: debug-container
      image: mcr.microsoft.com/dotnet/runtime-deps:6.0  # Lightweight container image with debugging tools
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
      command:
        - "/bin/sh"
        - "-c"
        - "sleep infinity"  # Keep the container running
      volumeMounts:
        - name: debug-volume
          mountPath: /mnt/azure/pvc  # Path where the volume will be mounted
  volumes:
    - name: debug-volume
      persistentVolumeClaim:
        claimName: {{ include "helm.fullname" . }}-azure-pvc
{{- end }}        