{{- if .Values.traefik.enabled -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ include "helm.fullname" . }}-ingress"
  namespace: {{ include "helm.namespace" . }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host:
      http:
        paths:
          - path: /{{ .Values.traefik.domainPath }}
            pathType: Prefix
            backend:
              service:
                name:  {{ include "helm.fullname" . }}
                port:
                  number: {{ .Values.image.containerPort }}
{{- end }}
