{{ if and (ne .Values.domainPath "") (hasKey .Values "stripPath") }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include "helm.fullname" . }}-strip"
  namespace: {{ include "helm.namespace" . }}
spec:
  stripPrefix:
    prefixes:
      - "/{{ .Values.domainPath }}"
{{ end }}
