apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: {{ include "helm.namespace" . }}
data:
  # data sources
  {{- $files := .Files }}
  {{- $datasourcesPath := .Values.grafana.datasourcesPath }}
  {{- if $datasourcesPath }}
  {{- range $path, $_ := $files.Glob (printf "%s/*.yaml" $datasourcesPath) }}
  {{ base $path }}: |-
{{ $files.Get $path | indent 4 }}
  {{- end }}
  {{- end }}