{{- if and .Values.azure.storage (hasKey .Values.azure.storage "create") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-fileshare
spec:
  template:
    spec:
      containers:
      - name: create-fileshare
        image: mcr.microsoft.com/azure-cli:2.43.0
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        command:
        - "/bin/sh"
        - "-c"
        - |
          az login --identity && \
          az storage share create --name {{ .Values.azure.storage.share }} \
          --account-name {{ .Values.azure.storage.account }}
        env:
        - name: AZURE_FEDERATED_TOKEN_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: AZURE_AUTHORITY_HOST
          value: https://login.microsoftonline.com/
        volumeMounts:
        - name: aad-msi-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
      - name: aad-msi-token
        secret:
          secretName: aad-msi-auth-token
          optional: true  # Make optional if the secret is not guaranteed
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/os: linux
{{- end }}