apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: {{ .Values.global.configCapacity }}
  hostPath:
    path: {{ .Values.global.configRoot }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.configCapacity }}
  storageClassName: ""
  volumeName: config-pv
  volumeMode: Filesystem