apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: {{ .Values.global.mediaCapacity }}
  hostPath:
    path: {{ .Values.global.mediaRoot }}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.mediaCapacity }}
  selector: {}
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: media-pv