{{- if hasKey .Values "postgres" }}
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-secret"
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
stringData:
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_HOSTNAME: {{ .Values.postgres.host }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DB: {{ .Values.postgres.database }}
{{- end }}