apiVersion: v1
kind: Secret
metadata:
  name: "transmission-vpn-secret"
data:
  OPENVPN_PASSWORD: {{ default .Values.transmission.vpn.password .Values.global.pia_password | b64enc }}
  TRANSMISSION_RPC_PASSWORD: {{ default .Values.transmission.password .Values.global.transmission_password | b64enc }}
stringData:
  OPENVPN_USERNAME: {{ default .Values.transmission.vpn.username .Values.global.pia_username }}
  TRANSMISSION_RPC_USERNAME: {{ default .Values.transmission.username .Values.global.transmission_username }}
