{{- if hasKey .Values.radarr "postgres" }}
apiVersion: v1
kind: Secret
metadata:
  name: "radarr-secret"
data:
  DATABASE_PASSWORD: {{ .Values.radarr.postgres.password | b64enc }}
stringData:
  DATABASE_USER: {{ .Values.radarr.postgres.user }}
{{- end }}