apiVersion: v1
kind: ConfigMap
metadata:
  name: "lidarr-startup"
data:
  config.xml: |
    <Config>
      <BindAddress>{{ .Values.lidarr.config.BindAddress }}</BindAddress>      
      <Port>{{ .Values.lidarr.config.Port }}</Port>      
      <SslPort>{{ .Values.lidarr.config.SslPort }}</SslPort>      
      <EnableSsl>{{ .Values.lidarr.config.EnableSsl }}</EnableSsl>      
      <LaunchBrowser>{{ .Values.lidarr.config.LaunchBrowser }}</LaunchBrowser>      
      <ApiKey>{{ default .Values.lidarr.config.ApiKey .Values.global.ApiKey }}</ApiKey>
      <AuthenticationMethod>{{ .Values.lidarr.config.AuthenticationMethod }}</AuthenticationMethod>      
      <AuthenticationRequired>{{ .Values.lidarr.config.AuthenticationRequired }}</AuthenticationRequired>
      <Branch>{{ .Values.lidarr.config.Branch }}</Branch>      
      <LogLevel>{{ .Values.lidarr.config.LogLevel }}</LogLevel>      
      <SslCertPath>{{ .Values.lidarr.config.SslCertPath }}</SslCertPath>      
      <SslCertPassword>{{ .Values.lidarr.config.SslCertPassword }}</SslCertPassword>      
      <UrlBase>{{ .Values.lidarr.config.UrlBase }}</UrlBase>
      <InstanceName>{{ .Values.lidarr.config.InstanceName }}</InstanceName>      
      <UpdateMechanism>{{ .Values.lidarr.config.UpdateMechanism }}</UpdateMechanism>      
    </Config>
