apiVersion: v1
kind: ConfigMap
metadata:
  name: "readarr-startup"
data:
  config.xml: |
    <Config>
      <BindAddress>{{ .Values.readarr.config.BindAddress }}</BindAddress>
      <Port>{{ .Values.readarr.config.Port }}</Port>
      <SslPort>{{ .Values.readarr.config.SslPort }}</SslPort>
      <EnableSsl>{{ .Values.readarr.config.EnableSsl }}</EnableSsl>
      <LaunchBrowser>{{ .Values.readarr.config.LaunchBrowser }}</LaunchBrowser>
      <ApiKey>{{ default .Values.readarr.config.ApiKey .Values.global.ApiKey }}</ApiKey>
      <AuthenticationMethod>{{ .Values.readarr.config.AuthenticationMethod }}</AuthenticationMethod>
      <AuthenticationRequired>{{ .Values.readarr.config.AuthenticationRequired }}</AuthenticationRequired>
      <Branch>{{ .Values.readarr.config.Branch }}</Branch>
      <LogLevel>{{ .Values.readarr.config.LogLevel }}</LogLevel>
      <SslCertPath>{{ .Values.readarr.config.SslCertPath }}</SslCertPath>
      <SslCertPassword>{{ .Values.readarr.config.SslCertPassword }}</SslCertPassword>
      <UrlBase>{{ .Values.readarr.config.UrlBase }}</UrlBase>
      <InstanceName>{{ .Values.readarr.config.InstanceName }}</InstanceName>
      <UpdateMechanism>{{ .Values.readarr.config.UpdateMechanism }}</UpdateMechanism>  
    </Config>