{{- if hasKey .Values.sonarr "postgres" }}
apiVersion: v1
kind: Secret
metadata:
  name: "sonarr-secret"
data:
  DATABASE_PASSWORD: {{ .Values.sonarr.postgres.password | b64enc }}
stringData:
  DATABASE_USER: {{ .Values.sonarr.postgres.user }}
{{- end }}